version: 4
services:
  mqsql:
    image: 8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/msql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql