version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoingit t-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: